# Generated by Django 5.0.7 on 2024-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.CharField(max_length=10)),
                ('isbn', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=100, max_digits=140000)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
